 
name: Deploy Lambda Function

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi

      - name: Create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zipped-bundle

      # - name: Upload file to S3
      #   uses: a-sync/s3-uploader@master
      #   with:
      #     args: --acl private
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ vars.AWS_REGION }}
      #     S3_BUCKET: ${{ vars.S3_BUCKET }}
      #     S3_KEY: ""
      #     FILE: ${{ github.sha }}.zip

      - name: Deploy Lambda Function
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          function_name: Hello-Microservice
          zip_file: ${{ github.sha }}.zip
          runtime: python3.9
          handler: function.lambda_handler